# Generated by Django 3.1.4 on 2020-12-03 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_blob', models.JSONField()),
                ('result', models.BooleanField()),
                ('is_person_on_sanction_list', models.BooleanField()),
                ('confirm_on_sanction_list', models.BooleanField()),
                ('status', models.CharField(choices=[('INIT', 'Initialized'), ('SC', 'Sanction Check'), ('PC', 'PEP Check'), ('AS', 'Assessment'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied')], default='INIT', max_length=20)),
            ],
        ),
    ]
