# Generated by Django 3.1.4 on 2020-12-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201203_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='result',
        ),
        migrations.AlterField(
            model_name='pep',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
